package example;


import org.openjdk.jmh.annotations.*;

import java.util.concurrent.TimeUnit;

@BenchmarkMode(Mode.AverageTime)
@OutputTimeUnit(TimeUnit.NANOSECONDS)
@Warmup(iterations = 2, time = 1, timeUnit = TimeUnit.SECONDS)
@Measurement(iterations = 10, time = 1, timeUnit = TimeUnit.SECONDS)
@Fork(7)
@State(Scope.Benchmark)
public class EnumValueOfBetweenDifferentSIzedEnumTests {

//    Benchmark                                                                                       Mode  Cnt  Score   Error  Units
//    EnumValueOfBetweenDifferentSIzedEnumTests.fiveHundrendishValueEnumValueOf_firstValue            avgt   70  3,161 ± 0,075  ns/op
//    EnumValueOfBetweenDifferentSIzedEnumTests.fiveHundrendishValueEnumValueOf_lastValue             avgt   70  2,853 ± 0,015  ns/op
//    EnumValueOfBetweenDifferentSIzedEnumTests.fiveHundrendishValueEnumValueOf_middleValue           avgt   70  2,844 ± 0,016  ns/op
//    EnumValueOfBetweenDifferentSIzedEnumTests.hundrendishValueEnumValueOf_firstValue                avgt   70  3,076 ± 0,057  ns/op
//    EnumValueOfBetweenDifferentSIzedEnumTests.hundrendishValueEnumValueOf_lastValue                 avgt   70  3,111 ± 0,084  ns/op
//    EnumValueOfBetweenDifferentSIzedEnumTests.hundrendishValueEnumValueOf_middleValue               avgt   70  3,204 ± 0,056  ns/op
//    EnumValueOfBetweenDifferentSIzedEnumTests.oneValueEnumValueOf                                   avgt   70  3,139 ± 0,039  ns/op
//    EnumValueOfBetweenDifferentSIzedEnumTests.superBigNamedHundrendishValueEnumValueOf_firstValue   avgt   70  2,904 ± 0,020  ns/op
//    EnumValueOfBetweenDifferentSIzedEnumTests.superBigNamedHundrendishValueEnumValueOf_lastValue    avgt   70  5,226 ± 0,042  ns/op
//    EnumValueOfBetweenDifferentSIzedEnumTests.superBigNamedHundrendishValueEnumValueOf_middleValue  avgt   70  2,975 ± 0,014  ns/op
//    EnumValueOfBetweenDifferentSIzedEnumTests.tenValueEnumValueOf_firstValue                        avgt   70  3,039 ± 0,063  ns/op
//    EnumValueOfBetweenDifferentSIzedEnumTests.tenValueEnumValueOf_lastValue                         avgt   70  3,029 ± 0,063  ns/op
//    EnumValueOfBetweenDifferentSIzedEnumTests.tenValueEnumValueOf_middleValue                       avgt   70  3,159 ± 0,013  ns/op
//    EnumValueOfBetweenDifferentSIzedEnumTests.threeValueEnumValueOf_firstValue                      avgt   70  3,108 ± 0,063  ns/op
//    EnumValueOfBetweenDifferentSIzedEnumTests.threeValueEnumValueOf_lastValue                       avgt   70  3,078 ± 0,065  ns/op
//    EnumValueOfBetweenDifferentSIzedEnumTests.threeValueEnumValueOf_middleValue                     avgt   70  3,139 ± 0,043  ns/op

    enum OneValueEnum {
        A
    }

    enum ThreeValueEnum {
        A, B, C
    }

    enum TenValueEnum {
        A, B, C, D, E, F, G, H, I, J
    }

    enum AlphabetValueEnum {
        A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z,

    }


    enum HundrendishValueEnum {
        A1, B1, C1, D1, E1, F1, G1, H1, I1, J1, K1, L1, M1, N1, O1, P1, Q1, R1, S1, T1, U1, V1, W1, X1, Y1, Z1, A2, B2, C2, D2, E2, F2, G2, H2, I2, J2, K2, L2, M2, N2, O2, P2, Q2, R2, S2, T2, U2, V2, W2, X2, Y2, Z2, A3, B3, C3, D3, E3, F3, G3, H3, I3, J3, K3, L3, M3, N3, O3, P3, Q3, R3, S3, T3, U3, V3, W3, X3, Y3, Z3, A4, B4, C4, D4, E4, F4, G4, H4, I4, J4, K4, L4, M4, N4, O4, P4, Q4, R4, S4, T4, U4, V4, W4, X4, Y4, Z4,

    }


    enum SuperBigNamedHundrendishValueEnum {
        A1_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, B1_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, C1_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, D1_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, E1_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, F1_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, G1_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, H1_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, I1_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, J1_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, K1_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, L1_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, M1_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, N1_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, O1_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, P1_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, Q1_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, R1_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, S1_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, T1_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, U1_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, V1_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, W1_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, X1_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, Y1_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, Z1_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, A2_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, B2_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, C2_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, D2_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, E2_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, F2_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, G2_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, H2_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, I2_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, J2_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, K2_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, L2_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, M2_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, N2_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, O2_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, P2_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, Q2_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, R2_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, S2_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, T2_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, U2_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, V2_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, W2_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, X2_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, Y2_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, Z2_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, A3_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, B3_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, C3_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, D3_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, E3_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, F3_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, G3_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, H3_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, I3_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, J3_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, K3_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, L3_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, M3_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, N3_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, O3_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, P3_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, Q3_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, R3_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, S3_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, T3_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, U3_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, V3_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, W3_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, X3_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, Y3_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, Z3_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, A4_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, B4_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, C4_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, D4_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, E4_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, F4_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, G4_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, H4_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, I4_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, J4_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, K4_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, L4_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, M4_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, N4_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, O4_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, P4_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, Q4_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, R4_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, S4_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, T4_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, U4_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, V4_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, W4_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, X4_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, Y4_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT, Z4_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT,

    }

    /**
     * Disguuuuuustiiiiiiiing - should get a proper format for this PC as well...
     **/
    enum FiveHundreshishValueEnum {
        A1, B1, C1, D1, E1, F1, G1, H1, I1, J1, K1, L1, M1, N1, O1, P1, Q1, R1, S1, T1, U1, V1, W1, X1, Y1, Z1, A2, B2, C2, D2, E2, F2, G2, H2, I2, J2, K2, L2, M2, N2, O2, P2, Q2, R2, S2, T2, U2, V2, W2, X2, Y2, Z2, A3, B3, C3, D3, E3, F3, G3, H3, I3, J3, K3, L3, M3, N3, O3, P3, Q3, R3, S3, T3, U3, V3, W3, X3, Y3, Z3, A4, B4, C4, D4, E4, F4, G4, H4, I4, J4, K4, L4, M4, N4, O4, P4, Q4, R4, S4, T4, U4, V4, W4, X4, Y4, Z4, A1_2, B1_2, C1_2, D1_2, E1_2, F1_2, G1_2, H1_2, I1_2, J1_2, K1_2, L1_2, M1_2, N1_2, O1_2, P1_2, Q1_2, R1_2, S1_2, T1_2, U1_2, V1_2, W1_2, X1_2, Y1_2, Z1_2, A2_2, B2_2, C2_2, D2_2, E2_2, F2_2, G2_2, H2_2, I2_2, J2_2, K2_2, L2_2, M2_2, N2_2, O2_2, P2_2, Q2_2, R2_2, S2_2, T2_2, U2_2, V2_2, W2_2, X2_2, Y2_2, Z2_2, A3_2, B3_2, C3_2, D3_2, E3_2, F3_2, G3_2, H3_2, I3_2, J3_2, K3_2, L3_2, M3_2, N3_2, O3_2, P3_2, Q3_2, R3_2, S3_2, T3_2, U3_2, V3_2, W3_2, X3_2, Y3_2, Z3_2, A4_2, B4_2, C4_2, D4_2, E4_2, F4_2, G4_2, H4_2, I4_2, J4_2, K4_2, L4_2, M4_2, N4_2, O4_2, P4_2, Q4_2, R4_2, S4_2, T4_2, U4_2, V4_2, W4_2, X4_2, Y4_2, Z4_2, A1_3, B1_3, C1_3, D1_3, E1_3, F1_3, G1_3, H1_3, I1_3, J1_3, K1_3, L1_3, M1_3, N1_3, O1_3, P1_3, Q1_3, R1_3, S1_3, T1_3, U1_3, V1_3, W1_3, X1_3, Y1_3, Z1_3, A2_3, B2_3, C2_3, D2_3, E2_3, F2_3, G2_3, H2_3, I2_3, J2_3, K2_3, L2_3, M2_3, N2_3, O2_3, P2_3, Q2_3, R2_3, S2_3, T2_3, U2_3, V2_3, W2_3, X2_3, Y2_3, Z2_3, A3_3, B3_3, C3_3, D3_3, E3_3, F3_3, G3_3, H3_3, I3_3, J3_3, K3_3, L3_3, M3_3, N3_3, O3_3, P3_3, Q3_3, R3_3, S3_3, T3_3, U3_3, V3_3, W3_3, X3_3, Y3_3, Z3_3, A4_3, B4_3, C4_3, D4_3, E4_3, F4_3, G4_3, H4_3, I4_3, J4_3, K4_3, L4_3, M4_3, N4_3, O4_3, P4_3, Q4_3, R4_3, S4_3, T4_3, U4_3, V4_3, W4_3, X4_3, Y4_3, Z4_3, A1_4, B1_4, C1_4, D1_4, E1_4, F1_4, G1_4, H1_4, I1_4, J1_4, K1_4, L1_4, M1_4, N1_4, O1_4, P1_4, Q1_4, R1_4, S1_4, T1_4, U1_4, V1_4, W1_4, X1_4, Y1_4, Z1_4, A2_4, B2_4, C2_4, D2_4, E2_4, F2_4, G2_4, H2_4, I2_4, J2_4, K2_4, L2_4, M2_4, N2_4, O2_4, P2_4, Q2_4, R2_4, S2_4, T2_4, U2_4, V2_4, W2_4, X2_4, Y2_4, Z2_4, A3_4, B3_4, C3_4, D3_4, E3_4, F3_4, G3_4, H3_4, I3_4, J3_4, K3_4, L3_4, M3_4, N3_4, O3_4, P3_4, Q3_4, R3_4, S3_4, T3_4, U3_4, V3_4, W3_4, X3_4, Y3_4, Z3_4, A4_4, B4_4, C4_4, D4_4, E4_4, F4_4, G4_4, H4_4, I4_4, J4_4, K4_4, L4_4, M4_4, N4_4, O4_4, P4_4, Q4_4, R4_4, S4_4, T4_4, U4_4, V4_4, W4_4, X4_4, Y4_4, Z4_4, A1_5, B1_5, C1_5, D1_5, E1_5, F1_5, G1_5, H1_5, I1_5, J1_5, K1_5, L1_5, M1_5, N1_5, O1_5, P1_5, Q1_5, R1_5, S1_5, T1_5, U1_5, V1_5, W1_5, X1_5, Y1_5, Z1_5, A2_5, B2_5, C2_5, D2_5, E2_5, F2_5, G2_5, H2_5, I2_5, J2_5, K2_5, L2_5, M2_5, N2_5, O2_5, P2_5, Q2_5, R2_5, S2_5, T2_5, U2_5, V2_5, W2_5, X2_5, Y2_5, Z2_5, A3_5, B3_5, C3_5, D3_5, E3_5, F3_5, G3_5, H3_5, I3_5, J3_5, K3_5, L3_5, M3_5, N3_5, O3_5, P3_5, Q3_5, R3_5, S3_5, T3_5, U3_5, V3_5, W3_5, X3_5, Y3_5, Z3_5, A4_5, B4_5, C4_5, D4_5, E4_5, F4_5, G4_5, H4_5, I4_5, J4_5, K4_5, L4_5, M4_5, N4_5, O4_5, P4_5, Q4_5, R4_5, S4_5, T4_5, U4_5, V4_5, W4_5, X4_5, Y4_5, Z4_5,

    }


    @Benchmark
    public static Object oneValueEnumValueOf() {
        return OneValueEnum.valueOf("A");
    }

    @Benchmark
    public static Object threeValueEnumValueOf_firstValue() {
        return ThreeValueEnum.valueOf("A");
    }

    @Benchmark
    public static Object threeValueEnumValueOf_middleValue() {
        return ThreeValueEnum.valueOf("B");
    }

    @Benchmark
    public static Object threeValueEnumValueOf_lastValue() {
        return ThreeValueEnum.valueOf("B");
    }

    @Benchmark
    public static Object tenValueEnumValueOf_firstValue() {
        return TenValueEnum.valueOf("A");
    }

    @Benchmark
    public static Object tenValueEnumValueOf_middleValue() {
        return TenValueEnum.valueOf("E");
    }

    @Benchmark
    public static Object tenValueEnumValueOf_lastValue() {
        return TenValueEnum.valueOf("J");
    }

    @Benchmark
    public static Object hundrendishValueEnumValueOf_firstValue() {
        return HundrendishValueEnum.valueOf("A1");
    }

    @Benchmark
    public static Object hundrendishValueEnumValueOf_middleValue() {
        return HundrendishValueEnum.valueOf("A3");
    }

    @Benchmark
    public static Object hundrendishValueEnumValueOf_lastValue() {
        return HundrendishValueEnum.valueOf("Z4");
    }


    @Benchmark
    public static Object superBigNamedHundrendishValueEnumValueOf_firstValue() {
        return SuperBigNamedHundrendishValueEnum.valueOf("A1_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT");
    }

    @Benchmark
    public static Object superBigNamedHundrendishValueEnumValueOf_middleValue() {
        return SuperBigNamedHundrendishValueEnum.valueOf("A3_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT");
    }

    @Benchmark
    public static Object superBigNamedHundrendishValueEnumValueOf_lastValue() {
        return SuperBigNamedHundrendishValueEnum.valueOf("Z4_SUPER_LONG_STRING_OF_CHARACTERS_MIGHT_AFFECT_PERFORMANCE_AS_WELL_AND_WE_NEED_TO_FIND_OUT");
    }


    @Benchmark
    public static Object fiveHundrendishValueEnumValueOf_firstValue() {
        return FiveHundreshishValueEnum.valueOf("A1");
    }

    @Benchmark
    public static Object fiveHundrendishValueEnumValueOf_middleValue() {
        return FiveHundreshishValueEnum.valueOf("A1_3");
    }

    @Benchmark
    public static Object fiveHundrendishValueEnumValueOf_lastValue() {
        return FiveHundreshishValueEnum.valueOf("Z4_5");
    }


}
